[build]
  pre_cmd = ["make clean"]
  cmd = "make build"
  bin = "./boilerplate"
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["Makefile", "go.mod", "go.sum", ".env"]
  exclude_dir = ["assets", "tmp", "vendor", ".idea", ".vscode"]
  delay = 1000

[log]
  level = "info"
